spring:
  application:
    name: nutri.api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/nutri_db}
    username: ${SPRING_DATASOURCE_USERNAME:nutri}
    password: ${SPRING_DATASOURCE_PASSWORD:nutri}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${SERVER_PORT:8082}

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration-minutes: ${JWT_EXPIRATION_MINUTES:15}
    refresh-token:
      session-hours: ${REFRESH_TOKEN_SESSION_HOURS:12}
      remember-days: ${REFRESH_TOKEN_REMEMBER_DAYS:30}
      secure-cookie: ${REFRESH_TOKEN_SECURE_COOKIE:false}
